name: Network VLAN Change (Manual)

on:
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Target device (e.g., edge1)'
        required: false
        type: string
        default: edge1
      target_interface:
        description: 'Target interface (e.g., GigabitEthernet0/1)'
        required: false
        type: string
        default: GigabitEthernet0/1
      target_vlan:
        description: 'Target VLAN ID'
        required: false
        type: string
        default: '20'
      skip_rollback:
        description: 'Skip automatic rollback'
        required: false
        type: boolean
        default: false
      environment:
        description: 'Environment to test against'
        required: false
        type: choice
        options:
          - lab
          - staging
          - production
        default: lab

jobs:
  run-network-pipeline:
    name: Launch reusable pipeline
    uses: ./.github/workflows/network-ci-cd.yml
    with:
      target_device: ${{ inputs.target_device }}
      target_interface: ${{ inputs.target_interface }}
      target_vlan: ${{ inputs.target_vlan }}
      skip_rollback: ${{ inputs.skip_rollback }}
      environment: ${{ inputs.environment }}
    secrets: inherit
